[package]
name = "poly2tri-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1"
imageproc = { version = "0.23", optional = true }
image = { version = "0.24", optional = true }
rusttype = { version = "0.9", optional = true }

[dev-dependencies]
rand = "0.8"
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false

[features]
default = []
draw = ["imageproc", "image", "rusttype"]